# <% require_relative 'chef_version' %>

driver:
  name: vagrant
  provider: veertu
  vagrantfiles:
    - veertu.rb
  customize:
    name: kitchen-docker-host
    cpus: <%= ENV['VB_CPUS'] || 4 %>
    memory: <%= ENV['VB_MEM'] || 4096 %>
  network:
    - ['forwarded_port', {guest: 2375, host: 2375}]
    - ['forwarded_port', {guest: 3128, host: 3128}]

transport:
  name: rsync

provisioner:
  name: chef_zero
  require_chef_omnibus: <%= CHEF_VERSION %>

platforms:
- name: centos-7.3
  driver:
    box: SaltwaterC/centos-7.3


suites:
- name: kdh
  run_list:
  - recipe[kitchen-docker-host]
